name: CI

on: [push]

jobs:

  build-groovy-example-2-5-6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: compile groovy-example
        run: ./gradlew :groovy-example-2-5-6:compileGroovy

  build-groovy-example-2-5-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: compile groovy-example
        run: ./gradlew :groovy-example-2-5-7:compileGroovy

  build-java-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: compile java-example
        run: ./gradlew :java-example:compileJava
